config/routes.rb
require 'subdomain'
Joinme::Application.routes.draw do

  

  devise_for :users, :controllers => {:sessions => "antdevise/sessions"} do
    get "userroot", :to => "users#userroot", :as => :user_root
  end

  constraints(Subdomain) do
    resources :comments
    resources :images, :only=>[:create, :destroy]

    resources :ideas do
      member do
        get :join 
        get :unjoin
        get :like
        post :invite
      end
    end

    get 'profile' => "users#profile"
    get 'members' => "users#index"

    match 'dashboard' => "ideas#dashboard", :as => :dashboard
    match '/' => 'ideas#dashboard'
  end
  root :to => "home#index"
  

end

app/models/idea.rb
class Idea < ActiveRecord::Base

	belongs_to :user
	belongs_to :company
	has_many :images, :dependent => :destroy
	has_many :idea_users, :dependent => :destroy
	has_many :users, :through => :idea_users
	has_many :comments, :dependent => :destroy

	def liked?(user)
		UserLike.count(:conditions=>{:user_id=>user.id, :idea_id=>id}) > 0
	end

	def like(user)
		UserLike.find(:first, :conditions=>{:user_id=>user.id, :idea_id=>id}) || UserLike.create(:user_id=>user.id, :idea_id=>id)
		update_attribute(:likes, likes + 1)
	end

end

app/controllers/ideas_controller.rb
class IdeasController < ApplicationController
  before_filter :authenticate_user!
  before_filter :check_owner, :only=>[:update, :destroy]

  # GET /dashboard
  # GET /dashboard.json
  def dashboard
    @ideas = current_user.company.ideas.order("likes DESC, created_at DESC")

    respond_to do |format|
      format.html # dashboard.html.erb
      format.json { render json: @ideas }
    end
  end

  
  # GET /ideas
  # GET /ideas.json
  def index
    return redirect_to(dashboard_path)

    @ideas = Idea.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @ideas }
    end
  end

  # GET /ideas/1
  # GET /ideas/1.json
  def show
    @idea = current_user.company.ideas.find(params[:id])
    @comment = Comment.new

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @idea }
    end
  end

  # GET /ideas/new
  # GET /ideas/new.json
  def new
    @idea = Idea.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @idea }
    end
  end

  # GET /ideas/1/edit
  def edit
    @idea = Idea.find(params[:id])
  end

  # POST /ideas
  # POST /ideas.json
  def create
    @idea = Idea.new(params[:idea])
    @idea.user_id = current_user.id
    @idea.company_id = current_user.company_id

    respond_to do |format|
      if @idea.save
        format.html { redirect_to @idea, notice: 'Idea was successfully created.' }
        format.json { render json: @idea, status: :created, location: @idea }
      else
        format.html { render action: "new" }
        format.json { render json: @idea.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /ideas/1
  # PUT /ideas/1.json
  def update
    respond_to do |format|
      if @idea.update_attributes(params[:idea])
        format.html { redirect_to @idea, notice: 'Idea was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @idea.errors, status: :unprocessable_entity }
      end
    end
  end

  def join
    @idea = Idea.find(params[:id])
    @idea.users << current_user
    redirect_to(@idea)
  end

  def unjoin
    @idea = Idea.find(params[:id])
    @idea.users.delete(current_user)
    redirect_to(@idea)
  end

  def like
    @idea = Idea.find(params[:id])
    @idea.like(current_user)
    respond_to do |format|
      format.html { redirect_to @idea }
      format.js
    end
  end

  def invite
    email = params[:user][:email].downcase
    idea = Idea.find(params[:id])
    user = User.find_by_email(email)
    
    unless user
      user = User.invite!(:email => email, :idea => idea)
    else
      Notifier.idea_invite(user, idea).deliver
    end

    redirect_to(idea, :notice => "Invitation email successfully sent to #{email}")
  end

  # DELETE /ideas/1
  # DELETE /ideas/1.json
  def destroy
    @idea.destroy

    respond_to do |format|
      format.html { redirect_to ideas_url }
      format.json { head :no_content }
    end
  end

  def check_owner
    @idea = Idea.find(params[:id])
    redirect_to(ideas_path, :alert=>"You are not an owner of this idea") if @idea.user != current_user
  end
end

app/helpers/ideas_helper.rb
module IdeasHelper
end

app/views/ideas/_form.html.erb
<%  stylesheet "form" %>
<div class="one_column">
  <div class="form center">
  <%= form_for(@idea) do |f| %>
    <% if @idea.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@idea.errors.count, "error") %> prohibited this idea from being saved:</h2>

        <ul>
        <% @idea.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    <% end %>
      <h3><%= @idea.id.nil? ? "New Great Idea" : "Change idea" %></h3>
    <div class="field">
      <%= f.text_field :title, :placeholder => "title" %>
    </div>
    <div class="field">
      <%= f.text_area :problem, :placeholder=>"Identify the idea/problem you have" %>
    </div>
    <div class="field">
      <%= f.text_area :solution, :placeholder=>"Suggest possible solution/implementation" %>
    </div>
    <div class="field">
      <%= f.text_area :requirements, :placeholder=>"Specify requirements/skills needed" %>
    </div>
    <div class="actions">
      <%= f.submit  :class=>"button big" %>
      <span style="float:right; padding-top: 40px">
      <%= link_to "Back", dashboard_path %>
      </span>
    </div>
  <% end %>
</div>
</div>

app/views/ideas/dashboard.html.erb
<% stylesheet "dashboard" %>
<div class="subheader">
    <div class="container_12">
        <div class="grid_8">
            <div class="h3">
                Discover Ideas
            </div>
            <div class="sub">
                See your co-workers ideas. Help them make it real.
            </div>
        </div>
        <div class="grid_4">
            <%= link_to "New Idea", new_idea_path() , :class=>"button" %>
        </div>
    </div>
</div>
<div class="content">
    <div class="container_12">
            <h3>Most popular</h3>

            <% @ideas.each do |idea| %>
              <div class="grid_4">
                <%= render :partial=>"shared/idea.html.erb", :locals=>{:idea=>idea} %>
              </div>
            <% end %>
            <div class="g-clear-20"></div>
    </div>
</div>

app/views/ideas/edit.html.erb
<%= render 'form' %>
<%= link_to 'Delete', @idea, confirm: "Are you sure?", method: :delete %>

app/views/ideas/index.html.erb
<h1>Listing ideas</h1>

<table>
  <tr>
    <th>Title</th>
    <th>Problem</th>
    <th>Solution</th>
    <th>Video</th>
    <th>Requirements</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @ideas.each do |idea| %>
  <tr>
    <td><%= idea.title %></td>
    <td><%= idea.problem %></td>
    <td><%= idea.solution %></td>
    <td><%= idea.video %></td>
    <td><%= idea.requirements %></td>
    <td><%= link_to 'Show', idea %></td>
    <td><%= link_to 'Edit', edit_idea_path(idea) %></td>
    <td><%= link_to 'Destroy', idea, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Idea', new_idea_path %>

app/views/ideas/like.js.erb
$("#likes").html("<%=@idea.likes %>");
$("#like_button").hide();

app/views/ideas/new.html.erb
<%= render 'form' %>

app/views/ideas/show.html.haml
- stylesheet "idea_show,comments"
.idea_header
  .container_12
    .grid_8
      %h1
        = @idea.title       
        - if @idea.user == current_user
          = link_to 'Edit', edit_idea_path(@idea)
      %idea_problem= @idea.problem
    .grid_4
      INVITE A COWORKER TO THIS IDEA
      = form_for(:user, :url=> invite_idea_path(@idea)) do |f|
        = f.text_field :email, class:"email", placeholder: "@#{current_user.company.domain}"
        = f.submit "SEND", :class=>"button invitebutton"

.idea_description
  .container_12
    .grid_8
      =image_tag @idea.images.first ? @idea.images.first.image.url(:med) : nil, size: "100%x373"
      .g-clear-20

      %b ABOUT THIS PROJECT
      .g-clear
      
      .horizontal-line
      
      = @idea.solution
      - if @idea.user == current_user
        .g-clear-20
        %h3 Manage photos
        = form_for Image.new, :html => { :multipart => true } do |f|
          = f.file_field :image
          = f.hidden_field :idea_id, :value=>@idea.id
          = f.submit "Upload", class: "button"
        - @idea.images.each do |i|
          %div
            %img{:height => "20px", :src => i.image.url(:thumb), :width => "20px"}/
            = link_to 'Destroy', i, confirm: 'Are you sure?', method: :delete

      .g-clear-20
      .comments
        .comment_form
          = form_for(@comment) do |f|
            - if @comment.errors.any?
              #error_explanation
                %h2
                  = pluralize(@comment.errors.count, "error")
                  prohibited this comment from being saved:
                %ul
                  - @comment.errors.full_messages.each do |msg|
                    %li= msg
            = f.text_area :comment, :placeholder =>"Leave your comment"
            = f.hidden_field :idea_id, :value => @idea.id
            = f.submit "Post", :class=>"button"
        .g-clear-20
        = render :partial => "shared/comment", :collection => @idea.comments
      .g-clear-20

      .g-clear
    .grid_4
      .actionbar
        .user
          .col_1=image_tag @idea.user.image ? @idea.user.image.url(:tiny2) : nil, size: "50x50"
          .col_2
            Creator:
            %br/
            = link_to @idea.user.full_name, profile_path(:id=>@idea.user.id)
        .g-clear-20
        
        .joined
          .col_1
            %numbers= (1 + @idea.users.count).to_s
          .col_2
            Supporters:
            %br/
            - @idea.users.each do |user|
              = link_to user.full_name, profile_path(:id=>user.id)

        - if @idea.users.include?(current_user)
          = link_to 'Leave this project', unjoin_idea_path(@idea) , confirm: 'Are you sure?', class: "button small"
        - else
          = link_to 'Join this project', join_idea_path(@idea), class: "button small"

        .liked
          .col_1
            %numbers= @idea.likes
          .col_2
            %br/
            liked this
        .g-clear
      .g-clear


/ .g-clear
/ .idea_content
/   .container_12
/     .grid_8.left{:style => "background-image: url('#{@idea.images.first ? @idea.images.first.image.url(:med) : nil}'); "}
/       .user
/         .photo{:style => "background-image: url('#{@idea.user.image ? @idea.user.image.url(:small) : nil}')"}
/         .about
/           %fullname= @idea.user.full_name
/           .g-clear-20
/           %department
/             Department: #{@idea.user.department}
/           %department
/             Title: #{@idea.user.title}
/       .g-clear

/     .grid_4
/       .center
/         .joined
/           %b#joined
/             = (1 + @idea.users.count).to_s
/           %br/
/           joined
/         .liked
/           %b#likes
/             = @idea.likes
/           %br/
/           liked this
/       .g-clear-20
/       - if @idea.user != current_user
/         .center
/           - if @idea.users.include?(current_user)
/             = link_to 'Leave', unjoin_idea_path(@idea) , confirm: 'Are you sure?', class: "large green awesome"
/           - else
/             = link_to 'Join', join_idea_path(@idea), :class=>"large green awesome"
/           - if @idea.liked?(current_user)
/           - else
/             = link_to 'Like', like_idea_path(@idea), class: "large green awesome", remote: true, id: "like_button"
/   .left
/     %p#notice= notice
/     %ideatitle
/       = @idea.title

/     %ideaproblem
/       Problem: #{@idea.problem}
/     %supporters
/       Participants:
/       - @idea.users.each do |user|
/         %a{:href => profile_path(:id=>user.id)}
/           %img{:height => "25px", :src => user.image.url(:tiny), :width => "25px"}/
/   .right
/     Requirements
/     %br/
/     - if @idea.requirements
/       - @idea.requirements.split("\n").each do |req|
/         %skill
/           = req
/     .g-clear-20
/     .invitation
/       %h3 Invite your co-worker help you out
/       = form_for(:user, :url=> invite_idea_path(@idea)) do |f|
/         = f.text_field :email, placeholder: "@#{current_user.company.domain}"
/         = f.submit "Invite", :class=>"button"
/   .g-clear
/ .idea_description
/   %div
/     Solution: #{@idea.solution}
/     - if @idea.user == current_user
/       .g-clear-20
/       %h3 Manage photos
/       = form_for Image.new, :html => { :multipart => true } do |f|
/         = f.file_field :image
/         = f.hidden_field :idea_id, :value=>@idea.id
/         = f.submit "Upload"
/       - @idea.images.each do |i|
/         %div
/           %img{:height => "20px", :src => i.image.url(:thumb), :width => "20px"}/
/           = link_to 'Destroy', i, confirm: 'Are you sure?', method: :delete
/   .g-clear-20
/ .comments
/   .comment_form
/     = form_for(@comment) do |f|
/       - if @comment.errors.any?
/         #error_explanation
/           %h2
/             = pluralize(@comment.errors.count, "error")
/             prohibited this comment from being saved:
/           %ul
/             - @comment.errors.full_messages.each do |msg|
/               %li= msg
/       = f.text_area :comment, :placeholder =>"Leave your comment"
/       = f.hidden_field :idea_id, :value => @idea.id
/       = f.submit "Post", :class=>"button"
/   .g-clear-20
/   = render :partial => "shared/comment", :collection => @idea.comments
/ %br/