config/routes.rb
require 'subdomain'
Joinme::Application.routes.draw do

  

  devise_for :users, :controllers => {:sessions => "antdevise/sessions"} do
    get "userroot", :to => "users#userroot", :as => :user_root
  end

  constraints(Subdomain) do
    resources :comments
    resources :images, :only=>[:create, :destroy]

    resources :ideas do
      member do
        get :join 
        get :unjoin
        get :like
        post :invite
      end
    end

    get 'profile' => "users#profile"
    get 'members' => "users#index"

    match 'dashboard' => "ideas#dashboard", :as => :dashboard
    match '/' => 'ideas#dashboard'
  end
  root :to => "home#index"
  

end

app/views/shared/_comment.html.erb
<div class="comment">
	<div class="comment_user">
		<a href="<%= profile_path(:id=>comment.user_id) %>">
			<img src="<%=comment.user.image.url(:tiny) %>" width="25px" height="25px"/><br/>
			<%= comment.user.full_name %>
		</a>
	</div>
	<div class="comment_body">
		<%= comment.comment %>
	</div>
	<div class="comment_actions">
		<% if comment.user == current_user %>
			<%= link_to "Edit", edit_comment_path(comment) %>
			| <%= link_to 'Delete', comment, confirm: 'Are you sure?', method: :delete %>
		<% end %>
	</div>
	<div class="g-clear"></div>
</div>

app/views/shared/_idea.html.erb
      <div class="idea">
        <div class="image"><a href="<%=idea_path(idea) %>"><img src="<%= idea.images.first ? idea.images.first.image.url(:thumb) : nil%>" width="260px" height="187px"></a></div>
        <div class="g-clear-10"></div>
        <div class="title"><%= link_to idea.title, idea_path(idea) %></div>
        <div class="g-clear-10"></div>
        <div class="owner">by <%=link_to idea.user.full_name, profile_path(:id=>idea.user.id) %></div>
        <div class="icons">
        	<span>
        		<img src="/images/joiners.png"/> <%= (1 + idea.users.count).to_s %>
        	</span>
        	<span>
        		<img src="/images/like.png"/> <%= idea.likes %>
        	</span>
        </div>
      </div>