config/routes.rb
require 'subdomain'
Joinme::Application.routes.draw do

  

  devise_for :users, :controllers => {:sessions => "antdevise/sessions"} do
    get "userroot", :to => "users#userroot", :as => :user_root
  end

  constraints(Subdomain) do
    resources :comments
    resources :images, :only=>[:create, :destroy]

    resources :ideas do
      member do
        get :join 
        get :unjoin
        get :like
        post :invite
      end
    end

    get 'profile' => "users#profile"
    get 'members' => "users#index"

    match 'dashboard' => "ideas#dashboard", :as => :dashboard
    match '/' => 'ideas#dashboard'
  end
  root :to => "home#index"
  

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Anthill</title>
  <%= stylesheet_link_tag    "application", "960", "text", "reset", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= stylesheet_link_tag *content_for(:stylesheets).split(",") if content_for?(:stylesheets) %>
  <%= javascript_include_tag *content_for(:javascripts).split(",") if content_for?(:javascripts) %>

  <%= csrf_meta_tags %>
</head>
<body>
<div class="header2">
  <div class="container_12">
  	<div class="grid_4 logo">
      <% if user_signed_in? %>
  		  <%= link_to "anthill for #{current_user.company.name}", dashboard_path %>
      <% else %>
        <%= link_to "anthill", root_url(:subdomain=>nil) %>
      <% end %>
  	</div>
  	<div class="grid_8 usermenu">
  		<% if user_signed_in? %>
        <%= link_to 'Dashboard', dashboard_path() %>
        <%= link_to 'Members', members_path() %>
        <%= link_to 'Profile', profile_path() %>
  	  	<%= link_to('Logout', destroy_user_session_url(:subdomain=>nil), :method => :delete) %>        
  		<% else %>
  		  <%= link_to('Login', root_path(:subdomain =>nil)) %>  
  	<% end %>
  	</div>
  </div>
</div>
<% if notice %>
  <div class="notice"><%= notice %></div>
<% end %>
<% unless alert.blank? %>
  <div class="alert"><%= alert %></div>
<% end %>
<%=yield %>

<script type="text/javascript">

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-32574909-1']);
  _gaq.push(['_setDomainName', 'getanthill.com']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

</script>
</body>
</html>

app/views/layouts/home.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Anthill</title>
  <%= stylesheet_link_tag    "application", "960", "text", "reset", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= stylesheet_link_tag content_for(:stylesheets) if content_for?(:stylesheets) %>
  <%= javascript_include_tag content_for(:javascripts) if content_for?(:javascripts) %>

  <%= csrf_meta_tags %>
</head>
<body>
<%= yield %>
<script type="text/javascript">

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-32574909-1']);
  _gaq.push(['_setDomainName', 'getanthill.com']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

</script>
</body>
</html>

app/views/layouts/logged.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Anthill</title>
  <%= stylesheet_link_tag    "application", "960", "text", "reset", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= stylesheet_link_tag content_for(:stylesheets) if content_for?(:stylesheets) %>
  <%= javascript_include_tag content_for(:javascripts) if content_for?(:javascripts) %>

  <%= csrf_meta_tags %>
</head>
<body>
<div class="header2">
	<div class="logo">
		<%= link_to "anthill", dashboard_path %>
	</div>
	<div class="usermenu">
		<%=link_to 'Dashboard', dashboard_path() %>
		<%=link_to 'Profile', profile_path() %>

		<% if user_signed_in? %>
	  	<%= link_to('Logout', destroy_user_session_path, :method => :delete) %>        
		<% else %>
		  <%= link_to('Login', root_path)  %>  
	<% end %>
	</div>
</div>
<%=yield %>

</body>
</html>